### ISSUE TITLE
[BUG] Footer doesn't stick to the bottom

### ISSUE THREAD

**Issue by CMihai99** [CMihai99/fyndro#4]
The page footer does not stick to the bottom of the page in situations where the page doesn't have a scrollbar.

To reproduce the behavior described above, go to any of the following pages:

  - about.html;
  - contact.html;
  - newsletter.html;
  - help.html;
  - index.html;

Screenshot(s):

![screenshot](https://user-images.githubusercontent.com/69072635/117330444-5f305180-ae9e-11eb-927e-9d8580a37784.png)

**Comment by goyal-Dushi** [comment]
Hey @CMihai99 , when I forked your repo to fix the issue, adding your footer section 

`{
position:absolute;
bottom:0;
}
`
Does the job.

So, I removed the section and instead used the HTML footer tag for the purpose, the styling is a bit out of place, but the issue is fixed.

After going through the code, I found that class names and other styling applied required improvement!.
Do you want me to fix those issues?

**Comment by CMihai99** [comment]
> Do you want me to fix those issues?

Hello @goyal-Dushi.
First of all, I am thankful for your contribution, second of all, I would gladly appreciate if you could fix at least a part of the code issues since I am not so experienced. If you managed to fix some of them, be sure to create a pull request and let me know.

Thanks in advance.

**Comment by goyal-Dushi** [comment]
Alright @CMihai99 , I will fix your footer then!
